### PR TITLE
[FIX] Clear relay cache after every build & Clear warning message cache after autotvm task extraction

### LINKED ISSUE #6096: apply_history_best requires extract_from_program to be run even if log file already exists
I'm running into a weird bug where `apply_history_best` doesn't work unless `extract_from_program` has been called somewhere before in the program (given the log file already exists).

Here is a minimal example:
```python
import os
import sys

import numpy as np
import tvm
from tvm import te
from tvm import autotvm
from tvm import relay
import tvm.relay.testing
from tvm.autotvm.tuner import XGBTuner, GATuner, RandomTuner, GridSearchTuner
from tvm.contrib.util import tempdir
import tvm.contrib.graph_runtime as runtime

input_shape = (1, 3, 224, 224)
output_shape = (1, 1000)

def run(mod, params, ctx):
    lib = relay.build(mod, target="llvm", params=params)

    dummy_data = np.random.uniform(size=input_shape).astype("float32")

    m = runtime.GraphModule(lib['default'](ctx))
    m.set_input('data', dummy_data)
    m.run()
    tvm_output = m.get_output(0)

    ftimer = m.module.time_evaluator("run", ctx, repeat=5, number=5)
    prof_res = np.array(ftimer().results) * 1000
    print(
        "%-20s %-19s (%s)"
        % ("Runtime:", "%.2f ms" % np.mean(prof_res), "%.2f ms" % np.std(prof_res))
    )


if __name__ == "__main__":
    mod, params = tvm.relay.testing.resnet.get_workload()

    ctx = tvm.cpu()
    print("Untuned")
    run(mod, params, ctx)

    log_filename = "bug_tuning.log"
    tmp_log_file = log_filename + ".tmp"
    if os.path.exists(tmp_log_file):
        os.remove(tmp_log_file)

    if sys.argv[1] == "tune" or sys.argv[1] == "extract":
        tasks = autotvm.task.extract_from_program(mod["main"], target="llvm",
                                                  params=params,
                                                  )

        if sys.argv[1] == "tune":
            for i, task in enumerate(tasks[0:4]):
                prefix = "[Task %2d/%2d] " % (i+1, len(tasks))
                tuner_obj = GridSearchTuner(task)

                # do tuning
                measure_option = autotvm.measure_option(
                        builder=autotvm.LocalBuilder(),
                        runner=autotvm.LocalRunner(number=10, repeat=1,
                                                   min_repeat_ms=1000),
                    )
                n_trial= min(len(task.config_space), 10)
                tuner_obj.tune(n_trial=n_trial,
                               early_stopping=False,
                               measure_option=measure_option,
                               callbacks=[
                                   autotvm.callback.progress_bar(n_trial, prefix=prefix),
                                   autotvm.callback.log_to_file(tmp_log_file)])

            # pick best records to a cache file
            autotvm.record.pick_best(tmp_log_file, log_filename)
            os.remove(tmp_log_file)

    print("Tuned")
    with autotvm.apply_history_best(log_filename):
        run(mod, params, ctx)
```

Run it like so:
```bash
python3 example.py tune
python3 example.py extract
python3 example.py run
```

On my laptop (macOS, quad-core 2.3GHz i7) I get the following output:
```
$ python3 simple_bug.py tune
Untuned
Cannot find config for target=llvm -keys=cpu, workload=('dense_nopack.x86', ('TENSOR', (1, 512), 'float32'), ('TENSOR', (1000, 512), 'float32'), None, 'float32'). A fallback configuration is used, which may bring great performance regression.
Runtime:             41.48 ms            (2.09 ms)
[Task  1/13]  Current/Best:   17.93/  34.07 GFLOPS | Progress: (10/10) | 27.28 s Done.
[Task  2/13]  Current/Best:    7.23/   7.24 GFLOPS | Progress: (10/10) | 18.49 s Done.
[Task  3/13]  Current/Best:   14.49/  14.49 GFLOPS | Progress: (10/10) | 22.80 s Done.
[Task  4/13]  Current/Best:   14.46/  14.46 GFLOPS | Progress: (10/10) | 18.14 s Done.
Tuned
Runtime:             178.57 ms           (1.56 ms)

$ python3 simple_bug.py extract
Untuned
Cannot find config for target=llvm -keys=cpu, workload=('dense_nopack.x86', ('TENSOR', (1, 512), 'float32'), ('TENSOR', (1000, 512), 'float32'), None, 'float32'). A fallback configuration is used, which may bring great performance regression.
Runtime:             40.87 ms            (0.60 ms)
Tuned
Runtime:             178.05 ms           (1.02 ms)

$ python3 simple_bug.py run
Untuned
Cannot find config for target=llvm -keys=cpu, workload=('dense_nopack.x86', ('TENSOR', (1, 512), 'float32'), ('TENSOR', (1000, 512), 'float32'), None, 'float32'). A fallback configuration is used, which may bring great performance regression.
Runtime:             40.37 ms            (0.75 ms)
Tuned
Runtime:             39.85 ms            (0.69 ms)
```

Ignore the fact that tuning makes results worse. I only run a couple iterations of the tuner to make the program run quickly.

On both `tune` and `extract`, the tuned performance is different from the untuned performance indicating that a tuned schedule was used. But on `run`, performance is the same between tuned and untuned. The only difference between `extract` and `run` is the call to `autotvm.task.extract_from_program`. I'm not clear what exactly the cause of this performance discrepancy is.

### PR DESCRIPTION
**Pull request by tkonolige**
Clear the compile cache between module builds so that schedule changes will have an effect. Also, clear the warning cache so that schedule changes properly list untuned ops.

Note: this makes `CompileEngine` a mutable global variable.

@merrymercy @jwfromm

### CODE REVIEW

File: src/relay/backend/build_module.cc [hunk 1]
```diff
@@ -225,6 +226,8 @@ class RelayBuildModule : public runtime::ModuleNode {
     targets_ = targets;
     target_host_ = target_host;
     BuildRelay(mod, params_);
+    // Clear compile engine so that tuning schedules can be changed between runs.
```
Comment (jroesch) [inline src/relay/backend/build_module.cc:229]: maybe put a back pointer to the issue so people can read more?

File: python/tvm/autotvm/task/relay_integration.py [hunk 2]
```diff
@@ -140,6 +140,11 @@ def extract_from_multiple_program(mods, params, target, target_host=None, ops=No
             build_thread.start()
             build_thread.join()
             relay.backend.compile_engine.get().clear()
+            # Clear the warning message cache in FallbackContext
+            from tvm.autotvm.task.dispatcher import DispatchContext, FallbackContext
```
Comment (comaniac) [inline python/tvm/autotvm/task/relay_integration.py:144]: Could we move the import to the top of this file?

File: src/relay/backend/compile_engine.cc [hunk 3]
```diff
@@ -770,7 +770,7 @@ class CompileEngineImpl : public CompileEngineNode {
 };
 
 /*! \brief The global compile engine */
-const CompileEngine& CompileEngine::Global() {
+CompileEngine& CompileEngine::Global() {
```
Comment (jwfromm) [inline src/relay/backend/compile_engine.cc:773]: What's the reason for dropping the `const` here?

**Comment by jwfromm** [comment]
@tkonolige, looks like the CI got aborted, can you rebase and push to trigger a new run?

File: src/relay/backend/compile_engine.cc (hunk 3 above)
Comment (tkonolige) [reply src/relay/backend/compile_engine.cc:773]: Clearing the cache mutates the `CompileEngine`, so in order to clear the cache after each build we need to modify the global state.

**Comment by tkonolige** [comment]
CI is getting errors like this:
```

>           raise get_last_ffi_error()
E           tvm._ffi.base.TVMError: Traceback (most recent call last):
E             [bt] (6) /workspace/build/libtvm.so(TVMFuncCall+0x65) [0x7f57e94d4785]
E             [bt] (5) /workspace/build/libtvm.so(+0xcc2606) [0x7f57e9567606]
E             [bt] (4) /workspace/build/libtvm.so(+0xcc24c3) [0x7f57e95674c3]
E             [bt] (3) /workspace/build/libtvm.so(tvm::runtime::GraphRuntime::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::Module, std::vector<DLContext, std::allocator<DLContext> > const&)+0x241) [0x7f57e9567141]
E             [bt] (2) /workspace/build/libtvm.so(tvm::runtime::GraphRuntime::SetupOpExecs()+0x591) [0x7f57e9566d01]
E             [bt] (1) /workspace/build/libtvm.so(tvm::runtime::GraphRuntime::CreateTVMOp(tvm::runtime::TVMOpParam const&, std::vector<DLTensor, std::allocator<DLTensor> > const&, unsigned long)+0x6e1) [0x7f57e9564dd1]
E             [bt] (0) /workspace/build/libtvm.so(+0xcbce12) [0x7f57e9561e12]
E             File "/workspace/src/runtime/graph/graph_runtime.cc", line 387
E           TVMError: Check failed: pf != nullptr: no such function in module: fused_add_subtract_concatenate

python/tvm/_ffi/_ctypes/packed_func.py:225: TVMError
```

I have no clue how this PR is triggering those errors.

**Comment by jwfromm** [comment]
@merrymercy, any idea why this change is triggering CI errors?

**Comment by merrymercy** [comment]
@tkonolige Can you reproduce the error locally?

**Comment by tkonolige** [comment]
@tkonolige I can reproduce the errors locally. Will look into it.

**Comment by tkonolige** [comment]
@tqchen @merrymercy I can't figure this error out. Could one of you take a look at it?

**Comment by tkonolige** [comment]
One of the failing tests is `tests/python/relay/test_external_runtime.py`. You can play around with it to try and debug.

**Comment by jroesch** [comment]
I pinged @zhiics since he is the owner afaik of this code, he said he would look at it tomorrow.

**Comment by zhiics** [comment]
Yeah, one quick thing I can do is to retire the example runtime since we have a real json runtime now. This example is not really use any more. I can send a PR later. cc @comaniac

**Comment by tkonolige** [comment]
@merrymercy @tqchen We can merge this now.
